### PR TITLE
upgrade(angular2): version to 0.40

### PR DESCRIPTION
**Pull request by valorkin**
Mega version bump >.<

### CODE REVIEW

**Comment by gdi2290** [comment]
you don't have to update all of the examples. That can be a separate PR

**Comment by valorkin** [comment]
npm set save-exact true
Is must have, will be done

**Comment by valorkin** [comment]
@gdi2290 taking in a count, how often we get broken updates from npm lately, all dependencies made immutable
Is it fine?

**Comment by gdi2290** [comment]
sounds good, feel free to merge

**Pull request merged**
