### PR TITLE
Fix: examples/large-app

### PR DESCRIPTION
**Pull request by dotcs**
I have fixed several issues with angular2@2.0.0-alpha.44. Furthermore I have fixed a broken import (see https://github.com/angular-class/angular2-webpack-starter/commit/a49383969f3729a73b1ac067c41e253b95556d53#commitcomment-13901195).

I also changed an import statement to keep the syntax the same across the application, because webpack complained about the import: 
> There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

There are still some issues with the 'search github' and 'todo' components, but the router does work again and at least webpack compiles without an error. This PR fixes https://github.com/angular-class/angular2-webpack-starter/issues/92.

### CODE REVIEW

**Comment by dotcs** [comment]
I forgot to mention that I have disabled the 'draggable_div' example because I could not find out how to include it properly. To me it seems as this component has been abandoned. Any help on how to include this component is appreciated.

**Comment by dotcs** [comment]
Update: I have fixed the 'search github' example in PR https://github.com/angular-class/angular2-webpack-starter/pull/107.

**Comment by SekibOmazic** [comment]
@dotcs Could you please rebase and resolve merge conflicts? Your PR also collides with #111 (although #111 just disables rxjs examples)

**Comment by dotcs** [comment]
@SekibOmazic Done. The I have enabled the rxjs examples again. With the fixes in #107 all rxjs examples are working fine again. Please give it a try.

**Comment by SekibOmazic** [comment]
LGTM

**Comment by SekibOmazic** [comment]
@dotcs Thanks!

**Pull request merged**
