### PR TITLE
fix(draggable.ts): Use toRx() of EventEmitter

### PR DESCRIPTION
**Pull request by SekibOmazic**
Use public method toRx() of EventEmitter insted of _subject.

### CODE REVIEW

**Comment by SekibOmazic** [comment]
@gdi2290 Maybe you could help. Mouse pointer jumps 8px up and 8px left (margin of body tag) when start dragging and then moves smoothly. Any clue why?

**Comment by dotcs** [comment]
@SekibOmazic The 8px offset comes from the browser's default margin of the body. If you set `body { margin: 0 }`, the problem is solved. We could fix it by removing the browser's default margin or perhaps it would be better to make use of [normalize.css](https://necolas.github.io/normalize.css/) or suchlike.

**Comment by SekibOmazic** [comment]
@dotcs Thanks. The `body { margin: 0 }` solves the problem. But I hoped it could be done without using/changing css.

**Comment by SekibOmazic** [comment]
@dotcs Sorry for bothering, but please take look at this example:

http://fiddle.jshell.net/mattpodwysocki/pfCqq/show/

It has `body {margin:0}` (loaded with bootstrap.min.css) but if you disable it and try to drag picture it works smoothly. You can even change margin to `body{margin 50px}` it still goes smoothly.

**Pull request merged**
