### PR TITLE
Update webpack.config.js

### PR DESCRIPTION
**Pull request by EladRK**
typo

### CODE REVIEW

**Comment by gdi2290** [comment]
thanks! haha if you could help me clean up and make the examples more clear that would be awesome

**Comment by EladRK** [comment]
We're now working on porting our knockout.js based website to angular 2, and as we're using your starter kit i'm pretty sure we'll stumble upon many things. I'm just glad I can give a hand back :)

**Comment by gdi2290** [comment]
@EladRK haha thanks but keep in mind angular2 is very early so it's not production ready yet. I would only suggest remaking it as a simple example

**Comment by EladRK** [comment]
shhhhh.. i just managed to convince upper management that it's safe enough - don't let them know!

we're starting a very needed refactoring and it'll take us no less than 3 months to merge this branch to production (hopefully). we're assuming that 3 months from now it'll be stable enough. for what we're doing now it's still unclear if we can actually working with it, but so far we haven't stumbled upon any showstoppers

**Pull request merged**
